### ISSUE TITLE
Unicode code point input

### ISSUE THREAD

**Issue by ghost** [ibus/ibus-m17n#4]
It appears that the Unicode code input on m17n differs subtly from the default (= English US). The default expects a space after entering unicode-code input state to terminate, while m17n jumps out after taking 4 hex digits as input. This causes issues with keyboards which exploit Unicode code input (notably qmk_firmware).

Could you please change this to conform to the default IME ? Otherwise, is it possible to change the behaviour within the mim files ? Thanks!

**Comment by mike-fabian** [comment]
It also causes the problem that you cannot enter Unicode characters above the basic multilingual
plane, for example 😎 U+1F60E like that because after typing Control+U 1F60 it already
commits and one gets ὠ U+1F60 GREEK SMALL LETTER OMEGA WITH PSILI.

What do you mean by “keyboards which exploit Unicode code input”?

**Comment by mike-fabian** [comment]
What you call the “default (= English US)” is the  Unicode input in ibus core. 
The Unicode input when using ibus-m17n comes from the file /usr/share/m17n/unicode.mim
which comes from the m17n database. ibus-m17n is only a frontend for this.

If you want to improve the Unicode input of ibus-m17n, you need to report this as a problem in
the m17n project, i.e. here: https://www.nongnu.org/m17n/

**Comment by mike-fabian** [comment]
I made a patch for unicode.mim to fix this problem:

https://lists.nongnu.org/archive/html/m17n-list/2022-02/msg00001.html
