### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ashinpan** [ibus/ibus-m17n#84]
**Describe the bug**
I failed to build the trunk version. 

**To Reproduce**
1. ./configure 
2. make 
3. error message:
make[2]: *** No rule to make target 'm17n.xml.in', needed by 'm17n.xml'.  Stop.
make[2]: Leaving directory '/home/pan/Develop/ibus-m17n/src'
make[1]: *** [Makefile:541: all-recursive] Error 1
make[1]: Leaving directory '/home/pan/Develop/ibus-m17n'
make: *** [Makefile:450: all] Error 2

**ibus-m17n version?**
github trunk version

**ibus version?**
1.5.29-rc2

**Distribution and version?**
Linux Mint 22 (Wilma) 

**Desktop and version?**
Cinnamon 6

**Xorg or Wayland?**
X11

**Comment by mike-fabian** [comment]
What do you mean by "trunk version"? Do you mean the "main" branch from the git checkout?

If you build from git, the procedure is:

```
./autogen.sh --prefix=/usr
make
```

You do not need to run configure then because `./autogen.sh --prefix=/usr` automatically runs `./configure --prefix=/usr` by default. You can give the arguments you would normally give to `./configure` to `./autogen.sh` (as I have shown above with the `--prefix=/usr` argument). You may also run `./configure` again after running `./autogen.sh`, that does not hurt but it does not change anything either.

Before running `./autogeh.sh` in a git checkout where all files not in git are not there (you can delete all files not in git with `git clean -dxf`) there is no `./configure`, this is created by running `./autogen.sh`. 

 If you are not building from git but from a downloaded release tarball like https://github.com/ibus/ibus-m17n/releases/download/1.4.31/ibus-m17n-1.4.31.tar.gz, then the `configure` file generated by `./autogen.sh` is already included in the tarball so you can run that directly, i.e. if building from a release tarball, you can do:

```
./configure --prefix=/usr
make
```

Anyway, in both cases, the `m17n.xml.in` is there:

- It is in the git repo: https://github.com/ibus/ibus-m17n/blob/main/src/m17n.xml.in
- And it is included in the release tarballs, here I confirm that it is there:
```
mfabian@hathi:/tmp
$ tar xvf ibus-m17n-1.4.31.tar.gz | grep xml.in
ibus-m17n-1.4.31/src/m17n.xml.in
mfabian@hathi:/tmp
$ 
```

Both ways, building from the git master branch and building from the latest release tarball work just fine for me.

I.e. I cannot see any problem here.

So what are you actually doing exactly? Can you give more details?

**Comment by ashinpan** [comment]
I mean the "main" branch from github. 

I git clone the repository anew again, and follow your instructions, i.e., "./autogen.sh --prefix=/usr" and "make." Now I have built and installed it successfully. Thanks a lot for your help.
