### ISSUE TITLE
[BUG] On Debian .c does not modify preceding character, only prints ऍ

### ISSUE THREAD

**Issue by aria-dos** [ibus/ibus-m17n#85]
**Describe the bug**
According to the [ITRANS unicode table](https://www.aczoom.com/itrans/online/itrans6/itrans-tables-unicode.pdf) and [documentation](https://www.aczoom.com/itrans/html/dvnc/node3.html), the key combination .c is supposed to modify the character preceding it it (e.g. ka.c -> कॅ , aa.c -> ऑ ), however when I try this, I get कऍ and आऍ respectively. Inputting .c thus returns ऍ , rather than modifying the previous character.

**To Reproduce**
1. Click on ibus tray icon.
2. Click on 'Hindi - hi-itrans (m17n)'.
3. Type 'aa.c' on US-style keyboard.
4. See it return 'आऍ'.

**Expected behavior**
I expected input 'aa.c' to return 'ऑ'.

**ibus-m17n version?**
ibus-m17n version is 1.4.19-1

**m17n-db versions?**
m17n-db version is 1.8.0-5

**ibus version?**
ibus version is 1.5.27

**Distribution and version?**
Debian version is Debian 12 (bookworm)

**Desktop and version?**
XFCE version is 4.18

**Xorg or Wayland?**
Using Xorg.

**Additional context**

**Comment by mike-fabian** [comment]
@aria-dos 

This is not a problem of ibus-m17n. 

It is a problem of the m17n input method hi-itrans.mim.

See here: https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/hi-itrans.mim

To get कॅ you can type `k.c` instead of `ka.c`.
To get ऑ you can type `o.c` instead of `aa.c`. 

It seems to work like that when using `hi-itrans.mim`, `mr-itrans.mim`, and `mr-gamabhana.mim`.

Whether this is good or bad I have no opinion about. It seems to disagree with the links you gave.

But as this is not an ibus-m17n problem, it is better to discuss this on the m17n mailing list. On that mailing list, the people who wrote or last edited `hi-itrans.mim`, `mr-itrans.mim`, and `mr-gamabhana.mim` can give their opinion and maybe improve something. 

Here is the home page of the m17n project: https://savannah.nongnu.org/projects/m17n/
And here is the mailing list: https://lists.nongnu.org/mailman/listinfo/m17n-list

**Comment by mike-fabian** [comment]
I did ask this question here on the mailing list:

https://lists.nongnu.org/archive/html/m17n-list/2024-09/msg00000.html

And I am closing this issue here.

**Comment by mike-fabian** [comment]
I made a new m17n-db release:

https://lists.nongnu.org/archive/html/m17n-list/2024-09/msg00003.html

It contains fixes by विश्वासो वासुकिजः (Vishvas Vasuki) in hi-itrans.mim which should fix the problems you reported  here.
